# packages.conf
# Format: <package_name>=<scope>[:target_path]
#   Packages should be in reference to a directory in the repository.
#       Example: common (refers to the '~/.dotfiles/common' directory)
#   Scopes:
#       all     -   For all systems
#       macos   -   For macOS systems only
#       fedora  -   For Fedora Linux systems only
#       ...     -   (additional scopes can be defined as needed)
# Example Entries:
#   common=all - Stows the 'common' package for all systems
#       ~/.dotfiles/common -> ~/common
#   prompts=macos:~/Library/Application Support/Code/User/prompts - Stows the 'prompts' package for macOS systems to a specific target path
#      ~/.dotfiles/prompts -> ~/Library/Application Support/Code/User/prompts

common=all
shell=all
git=all
macos=macos
fedora=fedora
.copilot=all
