# packages.conf
# Format: <package_name>=<scope>[:target_path]
#   Packages should be in reference to a directory in the repository.
#       Example: common (refers to the '~/.dotfiles/common' directory)
#       Nested example: os/macos (refers to the '~/.dotfiles/os/macos' directory)
#   Scopes:
#       all     -   For all systems
#       macos   -   For macOS systems only
#       fedora  -   For Fedora Linux systems only
#       ...     -   (additional scopes can be defined as needed)
# Example Entries:
#   common=all - Stows the 'common' package for all systems
#       ~/.dotfiles/common -> ~/common
#   os/macos=macos - Stows the '~/.dotfiles/os/macos' package for macOS systems
#   copilot=all:~/.copilot - Stows the '~/.dotfiles/copilot' package to a specific target path
#      ~/.dotfiles/copilot -> ~/.copilot

common=all
shell=all
git=all
os/macos=macos
os/fedora=fedora
os/debian=debian
copilot=all:~/.copilot
