cask_args appdir: '/Applications'

# Essential tools
brew 'git'
brew 'stow'

# Development tools
brew 'node'
brew 'python'
brew 'docker'
brew 'go'
brew 'rust'
brew 'java'
brew 'docker-compose'
brew 'ffmpeg'

# Applications
cask 'visual-studio-code'
cask 'iterm2'
cask 'spotify'
cask 'nikitabobko/tap/aerospace'
